networks:
  l0-test-net:
    driver: bridge

services:

  postgres:
    image: postgres:16
    container_name: l0-pg
    networks: [l0-test-net]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: layer0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d layer0"]
      interval: 5s
      timeout: 3s
      retries: 10

  l0-server:
    image: ghcr.io/bigt-ai-platform/test
    container_name: l0-svr
    networks: [l0-test-net]
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SERVER_NET: Test
      SERVER_MINERADDRESS: mjWvzPZz4YJtWqb7ux7cdgq5G7rzkg3bXG
      DB_HOSTNAME: postgres
      DB_PORT: 5432
      DB_NAME: layer0
      DB_USERNAME: root
      DB_PASSWORD: test1234
      DBTYPE: postgresql
      SERVICE_MINING: "false"
      SERVICE_SYNC: "true"
      SERVICE_INITSYNC: "true"
      SYNCBLOCKS: 1000
      CREATETABLE: "true"
    depends_on:
      postgres: { condition: service_healthy }
