version: '3.8'

networks:
  bigtangle-bridged-network:
    driver: bridge

services:
  bigtangle-seeds:
    image: ghcr.io/bigtangle/server:bigtangle-seeds-contract-latest

    container_name: bigtangle-seeds
    hostname: bigtangle-seeds
    networks:
      - bigtangle-bridged-network
    ports:
      - "8089:8089"
    environment:
      SSL: "true"
      KEYSTORE: /app/bigtangle-seeds/ca.pkcs12

