networks:
  bigtangle-bridged-network:
    driver: bridge

services:
  test-bigtangle-postgres:
    image: postgres:16
    container_name: test-bigtangle-postgres
    hostname: test-bigtangle-postgres
    networks:
      - bigtangle-bridged-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: info
    command: postgres -c max_connections=200
    volumes:
      - /data/vm/test-bigtangle-postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d info"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
 
