  
 
networks:
  bigtangle-bridged-network:
    driver: bridge

services:
  test-bigtangle-postgres:
    image: postgres:16
    container_name: test-bigtangle-postgres
    hostname: test-bigtangle-postgres
    networks:
      - bigtangle-bridged-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: info
    volumes:
      - /data/vm/test-bigtangle-postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d info"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    networks:
      - bigtangle-bridged-network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
      MINIO_DEFAULT_BUCKETS: testbigtangle
    volumes:
      - /data/vm/minio/minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  test-bigtangle:
    build:
      context: ..
      dockerfile: helper/bigtangle/Dockerfile
    image: bigtangle-server:local
    container_name: test-bigtangle
    hostname: test-bigtangle
    networks:
      - bigtangle-bridged-network
    ports:
      - "18089:18089"
    links:
      - test-bigtangle-postgres
    environment:
      JAVA_OPTS: "-Ddebug -Xmx5028m --add-exports java.base/sun.nio.ch=ALL-UNNAMED -Dfile.encoding=UTF-8"
      DB_PASSWORD: test1234
      DB_USER: root
      DB_PORT: 5432
      SERVER_PORT: 18089
      DB_NAME: info
      DB_HOSTNAME: test-bigtangle-postgres
      MINIO_URL: http://minio:9000
      MINIO_ACCESSKEY: minioadmin
      MINIO_SECRETKEY: minioadminpassword
      MINIO_BUCKETNAME: testbigtangle
      SERVER_MINERADDRESS: mjWvzPZz4YJtWqb7ux7cdgq5G7rzkg3bXG
      SERVERMODE: ""
      SERVER_REQUESTER: http://test-bigtangle:18089
      REQUESTER: http://test-bigtangle:18089

      SERVICE_CHAINLENGTH: "false"
      SERVER_RUN_KAFKA_STREAM: "false"
      SERVER_NET: Test
      SSL: "false"
    depends_on:
      - test-bigtangle-postgres
      - minio

    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    hostname: cloudflared
    networks:
      - bigtangle-bridged-network
    entrypoint: []
    command: ["cloudflared", "tunnel", "run"]
    restart: always
    volumes:
      - /home/jcui/git/server/helper/cloudflared-config.yml:/etc/cloudflared/config.yml:ro
      - /home/jcui/git/server/helper/credentials.json:/etc/cloudflared/credentials.json
