/*******************************************************************************
 *  Copyright   2018  Inasset GmbH.
 *
 *******************************************************************************/
package net.bigtangle.mcmc.test;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.apache.commons.lang3.tuple.Pair;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import net.bigtangle.core.Block;
import net.bigtangle.core.UtilGeneseBlock;
import net.bigtangle.server.core.BlockWrap;
import net.bigtangle.server.data.TipsQueue;

/**
 * Tests for verifying MCMC service generates tips from genesis block.
 *
 * This test demonstrates that when blocks are added to an empty database,
 * the MCMC service can successfully generate tips for new block creation.
 */
public class GenesisBlockTipsTest extends AbstractIntegrationTest {

	private static final Logger log = LoggerFactory.getLogger(GenesisBlockTipsTest.class);

	@Test
	public void testSingleBlockAndTipsGeneration() throws Exception {
		// Create a block referencing genesis as parents
		// Note: We use createGenesis as a reference for block creation, but don't add genesis itself
		Block genesis = UtilGeneseBlock.createGenesis(networkParameters);
		Block block1 = UtilsTest.createBlock(networkParameters, genesis, genesis);

		log.info("Block 1 created: " + block1.getHashAsString());

		// Add the block to the blockgraph
		blockGraph.addBlock(block1, true, store);

		// Verify block is stored
		BlockWrap block1Wrap = store.getBlockWrap(block1.getHash());
		assertNotNull(block1Wrap, "Block should be stored in database");

		log.info("Block 1 stored successfully with height: " + block1Wrap.getBlock().getHeight());

		// Update MCMC service to generate tips
		mcmcService.update(store);

		// Verify tips are generated by getting the TipsQueue
		TipsQueue tipsQueue = store.getTipsQueue();
		assertNotNull(tipsQueue, "Tips queue should not be null");
		assertNotNull(tipsQueue.getHash(), "Tips queue should have at least one tip");

		log.info("Tips generated - Height: " + tipsQueue.getHeight()
				+ ", InsertTime: " + tipsQueue.getInserttime());

		// Verify we can get a validated block pair
		Pair<BlockWrap, BlockWrap> tips = tipsService.getValidatedBlockPair(store);
		assertNotNull(tips, "Should be able to get validated block pair");
		assertNotNull(tips.getLeft(), "Left tip should not be null");
		assertNotNull(tips.getRight(), "Right tip should not be null");

		log.info("Validated block pair - Left: " + tips.getLeft().getBlockHash()
				+ ", Right: " + tips.getRight().getBlockHash());

		// Verify tips have valid heights
		assertTrue(tips.getLeft().getBlock().getHeight() >= 0);
		assertTrue(tips.getRight().getBlock().getHeight() >= 0);
	}

	@Test
	public void testMultipleBlocksAndTipsGeneration() throws Exception {
		// Create initial block chain starting from genesis reference
		Block genesis = UtilGeneseBlock.createGenesis(networkParameters);

		// Create first block
		Block block1 = createAndAddNextBlock(genesis, genesis);
		log.info("Block 1 added: " + block1.getHashAsString());

		// Create additional blocks building on top of each other
		Block block2 = createAndAddNextBlock(block1, block1);
		log.info("Block 2 added: " + block2.getHashAsString());

		Block block3 = createAndAddNextBlock(block2, block2);
		log.info("Block 3 added: " + block3.getHashAsString());

		Block block4 = createAndAddNextBlock(block3, block3);
		log.info("Block 4 added: " + block4.getHashAsString());

		log.info("Multiple blocks added successfully");

		// Update MCMC service
		mcmcServiceUpdate();

		// Verify tips are generated
		TipsQueue tipsQueue = store.getTipsQueue();
		assertNotNull(tipsQueue, "Tips queue should not be null after adding multiple blocks");
		assertTrue(tipsQueue.getHeight() > 0, "Tips height should be greater than 0");

		log.info("Tips after adding blocks - Height: " + tipsQueue.getHeight());

		// Get validated block pair multiple times to ensure consistency
		for (int i = 0; i < 5; i++) {
			Pair<BlockWrap, BlockWrap> tips = tipsService.getValidatedBlockPair(store);
			assertNotNull(tips, "Tips should not be null in iteration " + (i+1));
			assertNotNull(tips.getLeft(), "Left tip should not be null");
			assertNotNull(tips.getRight(), "Right tip should not be null");

			log.info("Iteration " + (i+1) + " - Tips: "
					+ tips.getLeft().getBlockHash() + ", "
					+ tips.getRight().getBlockHash());
		}
	}

	@Test
	public void testTipsUpdateAfterNewBlocks() throws Exception {
		// Start with one block
		Block genesis = UtilGeneseBlock.createGenesis(networkParameters);
		Block block1 = createAndAddNextBlock(genesis, genesis);

		log.info("Initial block added: " + block1.getHashAsString());

		// Update MCMC and get tips
		mcmcService.update(store);
		TipsQueue initialTips = store.getTipsQueue();
		assertNotNull(initialTips, "Initial tips should not be null");
		long initialHeight = initialTips.getHeight();

		log.info("Initial tips - Height: " + initialHeight);

		// Add more blocks
		Block block2 = createAndAddNextBlock(block1, block1);
		Block block3 = createAndAddNextBlock(block2, block2);

		log.info("Added 2 more blocks");

		// Update MCMC again
		mcmcServiceUpdate();

		// Verify tips are updated
		TipsQueue updatedTips = store.getTipsQueue();
		assertNotNull(updatedTips, "Updated tips should not be null");
		long updatedHeight = updatedTips.getHeight();

		log.info("Updated tips - Height: " + updatedHeight);
		assertTrue(updatedHeight >= initialHeight, "Tips height should increase or stay same after adding blocks");

		// Verify validated block pairs are still available
		Pair<BlockWrap, BlockWrap> tips = tipsService.getValidatedBlockPair(store);
		assertNotNull(tips);
		assertNotNull(tips.getLeft());
		assertNotNull(tips.getRight());

		log.info("Tips still valid after updates");
	}
}
