package net.bigtangle.crypto.pq;

import static org.junit.jupiter.api.Assertions.*;

import java.nio.charset.StandardCharsets;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import net.bigtangle.core.Sha256Hash;
import net.bigtangle.core.Utils;

/**
 * Cross-platform PQ signature compatibility test.
 *
 * Verifies that signatures produced by the TypeScript @noble/post-quantum
 * library (ML-DSA-87 + SLH-DSA-SHA2-256s) can be verified by the Java
 * BouncyCastle implementation used on the server.
 *
 * Test vectors are generated by:
 *   packages/bigtangle-ts/scripts/gen-pq-test-vectors.mjs
 */
class PQCrossPlatformCompatTest {

    private static BcPQSignatureProvider provider;

    @BeforeAll
    static void setUp() {
        provider = new BcPQSignatureProvider();
        PQScriptUtils.setProvider(provider);
    }

    @Test
    void nobleMLDSASignatureVerifiesWithBC() {
        // Test vector: TypeScript @noble/post-quantum signed "cross-platform-pq-test"
        // using PQKey.fromSeeds(0x42 × 32, 0x24 × 32)
        String pubKeyHex   = "050102010a2042424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242424242"
                + "02010a2064000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000000000000640000000000000000000000000000000000000000000000000000000000000064";
        String sigHex      = "";
        String baseHashHex = "7ca96eb7910093b87f2c6e4439709c41eece126290f7dcfd3528797ccfe1c48e";

        byte[] pubKey = Utils.HEX.decode(pubKeyHex);
        byte[] sigBytes = Utils.HEX.decode(sigHex);
        Sha256Hash baseHash = Sha256Hash.wrap(Utils.HEX.decode(baseHashHex));

        boolean valid = PQScriptUtils.verifyPQ(pubKey, sigBytes, baseHash);
        assertTrue(valid, "TypeScript noble PQ signature should verify with Java BC");
    }
}
