<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>bigtangle</artifactId>
		<groupId>net.bigtangle</groupId>
		<version>0.5.0</version>
	</parent>

	<artifactId>layer0-mcmc</artifactId>
	<packaging>jar</packaging>
	<dependencies>

		<dependency>
			<groupId>net.bigtangle</groupId>
			<artifactId>layer0-servercore</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>net.bigtangle</groupId>
			<artifactId>layer0-server</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>


		<dependency>
			<groupId>net.bigtangle</groupId>
			<artifactId>bigtangle-bridge</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>net.bigtangle</groupId>
			<artifactId>l1-contract-server</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<version>${org.springframework.boot.version}</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.jgrapht</groupId>
			<artifactId>jgrapht-core</artifactId>
			<version>1.5.2</version>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>src/test/resources</directory>
			</testResource>
		</testResources>
		<plugins>

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>3.2.1</version>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
						<configuration>
							<classifier>exec</classifier>
							<mainClass>net.bigtangle.layer0.mcmc.Layer0MCMCStart</mainClass>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>17</source>
					<target>17</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<forkCount>0</forkCount>
					<redirectTestOutputToFile>true</redirectTestOutputToFile>
					<excludes>
						<exclude>**/net/bigtangle/mcmc/remote/**</exclude>
						<exclude>**/net/bigtangle/performance/**</exclude>
					</excludes>
				</configuration>
			</plugin>

			<plugin>
				<groupId>pl.project13.maven</groupId>
				<artifactId>git-commit-id-plugin</artifactId>
				<version>4.9.10</version>
			</plugin>

		</plugins>
	</build>
</project>
