name: Integration Tests with PostgreSQL

on:
  push:
    branches:
      - main
      - contract
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: info
          POSTGRES_USER: root
          POSTGRES_PASSWORD: test1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      minio:
        image: minio/minio:latest
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
          MINIO_DEFAULT_BUCKETS: testbigtangle
          GITHUB_ACTIONS: "true"
          CI: "true"
        ports:
          - 9000:9000
          - 9001:9001


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven



      - name: Run Maven integration tests
        run: mvn -B package  -Dsurefire.excludes=**/performance/**  --file pom.xml 
        env:
          MAVEN_OPTS: -Xmx4g -Xms1g
