#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PREPROD="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_FILE="${PREPROD}/docker-compose.pos.yml"
COMPOSE_PROJECT="l0-pos-preprod"

DEFAULT_NODE_COUNT=16
DEFAULT_IMAGE_TAG="preprod"
DEFAULT_MINER_ADDR="mjWvzPZz4YJtWqb7ux7cdgq5G7rzkg3bXG"
DEFAULT_NET="Preprod"
DEFAULT_JAVA_MEM_MB=1024

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[preprod]${NC} $*"; }
warn() { echo -e "${YELLOW}[preprod]${NC} $*"; }
err()  { echo -e "${RED}[preprod]${NC} $*" >&2; }
info() { echo -e "${CYAN}[preprod]${NC} $*"; }

usage() {
  cat <<EOF
Usage: ./run.sh <command> [options]

Commands:
  build       Build Docker image (requires Maven build first)
  generate    Generate docker-compose YAML for N nodes
  up          Start the preprod PoS network
  down        Stop and remove all containers
  restart     Restart the network
  status      Show container status
  logs        Tail logs from a node (e.g., ./run.sh logs svr-0)
  clean       Remove all containers, volumes, and generated files
  ps          Alias for status
  help        Show this help

Options:
  --nodes N           Number of PoS nodes (default: ${DEFAULT_NODE_COUNT})
  --tag TAG           Docker image tag (default: ${DEFAULT_IMAGE_TAG})
  --miner ADDRESS     Miner reward address (default: ${DEFAULT_MINER_ADDR})
  --net NAME          Network name (default: ${DEFAULT_NET})
  --mem MB            Java heap per JVM in MB (default: ${DEFAULT_JAVA_MEM_MB})
  --no-rebuild        Skip Maven build before Docker build

Examples:
  ./run.sh build --no-rebuild
  ./run.sh up --nodes 32
  ./run.sh generate --nodes 16
  ./run.sh logs svr-2
  ./run.sh down && ./run.sh up --nodes 8
EOF
  exit 0
}

# ─── Parse options ──────────────────────────────────────────────────

NODE_COUNT="${DEFAULT_NODE_COUNT}"
IMAGE_TAG="${DEFAULT_IMAGE_TAG}"
MINER_ADDR="${DEFAULT_MINER_ADDR}"
NET_NAME="${DEFAULT_NET}"
JAVA_MEM="${DEFAULT_JAVA_MEM_MB}"
REBUILD_MAVEN=true

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --nodes)    NODE_COUNT="$2";   shift 2 ;;
      --tag)      IMAGE_TAG="$2";    shift 2 ;;
      --miner)    MINER_ADDR="$2";   shift 2 ;;
      --net)      NET_NAME="$2";     shift 2 ;;
      --mem)      JAVA_MEM="$2";     shift 2 ;;
      --no-rebuild) REBUILD_MAVEN=false; shift ;;
      --help|-h)  usage ;;
      *)          break ;;
    esac
  done
}

# ─── Validator key generation ───────────────────────────────────────

generate_validator_key() {
  local node_idx="$1"
  printf "preprod-validator-key-%02x%04x" "${node_idx}" "${node_idx}" \
    | sha256sum | cut -c1-64
}

export_validator_keys() {
  for ((i=0; i<NODE_COUNT; i++)); do
    local key; key="$(generate_validator_key "$i")"
    export "POS_VALIDATOR_KEY_${i}=${key}"
  done
}

# ─── Compose file resolution ────────────────────────────────────────

resolve_compose_file() {
  local count="$1"
  if [[ "$count" -le 4 && -f "${COMPOSE_FILE}" ]]; then
    echo "${COMPOSE_FILE}"
  else
    local gen="${PREPROD}/.docker-compose.pos-${count}.generated.yml"
    maybe_generate_compose "$count" "$gen"
    echo "$gen"
  fi
}

maybe_generate_compose() {
  local count="$1"
  local out="$2"
  if [[ -f "$out" ]]; then
    return
  fi
  generate_compose_yaml "$count" "$out"
}

# ─── Compose YAML generation ────────────────────────────────────────

generate_compose_yaml() {
  local count="$1"
  local out="$2"
  info "Generating compose file for ${count} nodes: ${out}"

  cat > "$out" <<YAML
# Auto-generated by run.sh --nodes ${count}
# Do not edit manually — re-run to regenerate.

networks:
  pos-preprod-net:
    driver: bridge

services:
YAML

  for ((i=0; i<count; i++)); do
    local pg_port=""
    [[ "$i" -eq 0 ]] && pg_port="5432"
    local svr_port=$((8081 + i))
    local mcmc_port=$((8085 + i))
    local db_host="postgres-l0-${i}"
    local requester=""
    local createtable="true"
    if [[ "$i" -gt 0 ]]; then
      requester="http://pos-svr-0:8081"
      createtable="false"
    fi

    # Pinned PG data path for node-0, others use anonymous volumes
    local pg_volumes=""
    if [[ "$i" -eq 0 ]]; then
      pg_volumes="    volumes:
      - pgdata-0:/var/lib/postgresql/data
"
    fi

    cat >> "$out" <<YAML

  # ─── Node ${i} ────────────────────────────────────────────────────────

  postgres-l0-${i}:
    image: postgres:16
    container_name: pos-pg-${i}
    networks: [pos-preprod-net]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: layer0
${pg_volumes}    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d layer0"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  l0-server-${i}:
    image: bigtangle:${IMAGE_TAG}
    container_name: pos-svr-${i}
    networks: [pos-preprod-net]
    ports: ["${svr_port}:${svr_port}"]
    environment:
      JAVA_OPTS: "-Xmx${JAVA_MEM}m -Xms256m"
      SERVER_PORT: ${svr_port}
      SERVER_NET: ${NET_NAME}
      SERVER_MINERADDRESS: ${MINER_ADDR}
      DB_HOSTNAME: ${db_host}
      DB_PORT: 5432
      DB_NAME: layer0
      DB_USERNAME: root
      DB_PASSWORD: test1234
      DBTYPE: postgresql
      SERVICE_MINING: "false"
      SERVICE_MCMC: "true"
      SERVICE_MCMC_RATE: 1000
      SERVICE_SYNC: "true"
      SERVICE_INITSYNC: "true"
      SYNCBLOCKS: 1000
      CREATETABLE: "${createtable}"
      POS_ENABLED: "true"
      POS_SLOT_INTERVAL_MS: 12000
      POS_SLOTS_PER_EPOCH: 32
YAML
    if [[ -n "$requester" ]]; then
      echo "      REQUESTER: ${requester}" >> "$out"
    fi
    cat >> "$out" <<YAML
    depends_on:
      postgres-l0-${i}: { condition: service_healthy }

  l0-mcmc-${i}:
    image: bigtangle:${IMAGE_TAG}
    container_name: pos-mcmc-${i}
    networks: [pos-preprod-net]
    ports: ["${mcmc_port}:${mcmc_port}"]
    environment:
      JAVA_OPTS: "-Xmx${JAVA_MEM}m -Xms256m"
      APP_MODULE: layer0-mcmc
      SERVER_PORT: ${mcmc_port}
      SERVER_NET: ${NET_NAME}
      SERVER_MINERADDRESS: ${MINER_ADDR}
      REQUESTER: http://pos-svr-${i}:${svr_port}
      DB_HOSTNAME: ${db_host}
      DB_PORT: 5432
      DB_NAME: layer0
      DB_USERNAME: root
      DB_PASSWORD: test1234
      DBTYPE: postgresql
      SERVICE_MINING: "true"
      SERVICE_MINING_RATE: 50000
      SERVICE_MCMC: "true"
      SERVICE_MCMC_RATE: 1000
      SERVICE_SYNC: "true"
      SERVICE_INITSYNC: "true"
      SYNCBLOCKS: 1000
      CREATETABLE: "false"
      POS_ENABLED: "true"
      POS_SLOT_INTERVAL_MS: 12000
      POS_SLOTS_PER_EPOCH: 32
      POS_VALIDATOR_KEY: "\${POS_VALIDATOR_KEY_${i}}"
    depends_on:
      postgres-l0-${i}: { condition: service_healthy }
      l0-server-${i}: { condition: service_started }

YAML
  done

  if [[ "$count" -gt 0 ]]; then
    echo "volumes:" >> "$out"
    echo "  pgdata-0:" >> "$out"
  fi

  log "Generated: ${out}"
}

# ─── Docker Compose wrapper ────────────────────────────────────────

compose() {
  local compose_file="$1"; shift
  docker compose -f "$compose_file" -p "${COMPOSE_PROJECT}" "$@"
}

# ─── Resource check ─────────────────────────────────────────────────

check_resources() {
  local count="$1"
  local total_jvms=$((count * 2))
  local total_mem_mb=$((total_jvms * JAVA_MEM))
  local total_containers=$((count * 3))

  info "Node count: ${count}"
  info "Containers: ${total_containers} (${count}×PG + ${count}×server + ${count}×mcmc)"
  info "JVM heaps:  ${total_jvms} × ${JAVA_MEM}m = ${total_mem_mb} MB total"
  info "Exposed ports: ${count}×server (8081-$((8080+count))) + ${count}×mcmc ($((8085))-$((8084+count)))"

  local docker_mem
  docker_mem="$(docker info 2>/dev/null | awk '/Total Memory/ {print $3, $4}')" || true
  if [[ -n "$docker_mem" ]]; then
    local docker_mem_mb
    docker_mem_mb="$(echo "$docker_mem" | sed 's/GiB/ * 1024/' | sed 's/MiB//' | bc 2>/dev/null || echo "?")"
    if [[ "$docker_mem_mb" != "?" ]] && [[ "$total_mem_mb" -gt "$docker_mem_mb" ]]; then
      warn "Total JVM heap (${total_mem_mb}m) exceeds Docker host memory (~${docker_mem_mb}m)!"
      warn "Reduce --nodes or --mem to avoid OOM kills."
    fi
  fi
}

# ─── Wait for all server nodes to be healthy (parallel) ────────────

wait_for_nodes() {
  local count="$1"
  local timeout="${2:-300}"
  info "Waiting up to ${timeout}s for ${count} server node(s) to become ready..."

  local start; start="$(date +%s)"
  local remaining=()
  for ((i=0; i<count; i++)); do
    remaining+=("$i")
  done

  while [[ ${#remaining[@]} -gt 0 ]]; do
    local elapsed=$(( $(date +%s) - start ))
    if [[ "$elapsed" -ge "$timeout" ]]; then
      err "Timeout (${timeout}s) reached. Unhealthy nodes: ${remaining[*]}"
      return 1
    fi

    local new_remaining=()
    for idx in "${remaining[@]}"; do
      local port=$((8081 + idx))
      if curl -sf "http://localhost:${port}/actuator/health" >/dev/null 2>&1; then
        echo "  node-${idx} (:${port}) ready"
      else
        new_remaining+=("$idx")
      fi
    done
    remaining=("${new_remaining[@]}")

    if [[ ${#remaining[@]} -gt 0 ]]; then
      sleep 3
    fi
  done

  local elapsed=$(( $(date +%s) - start ))
  log "All ${count} nodes ready in ${elapsed}s"
}

# ─── Build ─────────────────────────────────────────────────────────

cmd_build() {
  if [[ "${REBUILD_MAVEN}" == true ]]; then
    log "Running Maven build (skipping tests)..."
    cd "${ROOT}"
    mvn -DskipTests clean install
  fi

  log "Building Docker image with tag '${IMAGE_TAG}'..."
  docker build -t "bigtangle:${IMAGE_TAG}" -f "${ROOT}/helper/bigtangle/Dockerfile" "${ROOT}"
  log "Docker image built: bigtangle:${IMAGE_TAG}"
}

# ─── Generate Compose ──────────────────────────────────────────────

cmd_generate() {
  local out="${PREPROD}/docker-compose.pos-${NODE_COUNT}.yml"
  generate_compose_yaml "${NODE_COUNT}" "$out"
  log "Run with: docker compose -f ${out} -p ${COMPOSE_PROJECT} up -d"
}

# ─── Up ────────────────────────────────────────────────────────────

cmd_up() {
  export_validator_keys
  check_resources "${NODE_COUNT}"

  local compose_file
  compose_file="$(resolve_compose_file "${NODE_COUNT}")"

  log "Starting PoS preprod network with ${NODE_COUNT} node(s) (compose: ${compose_file})..."
  compose "$compose_file" up -d --remove-orphans
  log "Network started."
  wait_for_nodes "${NODE_COUNT}"
}

# ─── Down ──────────────────────────────────────────────────────────

cmd_down() {
  log "Stopping PoS preprod network..."

  local compose_file
  compose_file="$(resolve_compose_file "${NODE_COUNT}")"

  compose "$compose_file" down --remove-orphans
  log "Network stopped."
}

# ─── Restart ───────────────────────────────────────────────────────

cmd_restart() {
  cmd_down
  cmd_up
}

# ─── Status ────────────────────────────────────────────────────────

cmd_status() {
  local compose_file
  compose_file="$(resolve_compose_file "${NODE_COUNT}")"
  compose "$compose_file" ps
}

# ─── Logs ──────────────────────────────────────────────────────────

cmd_logs() {
  local target="${1:-}"
  local compose_file
  compose_file="$(resolve_compose_file "${NODE_COUNT}")"

  if [[ -z "${target}" ]]; then
    compose "$compose_file" logs --tail=50 -f
  else
    compose "$compose_file" logs --tail=100 -f "pos-${target}"
  fi
}

# ─── Clean ─────────────────────────────────────────────────────────

cmd_clean() {
  warn "Stopping and removing all containers, volumes, and generated files..."

  # Find any generated compose file and tear down
  for f in "${PREPROD}"/.docker-compose.pos-*.generated.yml "${PREPROD}"/docker-compose.pos-*.yml; do
    [[ -f "$f" ]] || continue
    docker compose -f "$f" -p "${COMPOSE_PROJECT}" down -v --remove-orphans 2>/dev/null || true
  done

  # Clean generated files
  local gens
  gens="$(ls "${PREPROD}"/.docker-compose.pos-*.generated.yml "${PREPROD}"/docker-compose.pos-*.yml 2>/dev/null || true)"
  for f in ${gens}; do
    if [[ "$(basename "${f}")" != "docker-compose.pos.yml" ]]; then
      rm -f "${f}"
      info "Removed: ${f}"
    fi
  done

  log "Clean complete."
}

# ─── Main ──────────────────────────────────────────────────────────

main() {
  if [[ $# -eq 0 ]]; then
    usage
  fi

  local cmd="$1"
  shift
  parse_args "$@"

  case "${cmd}" in
    build)     cmd_build ;;
    generate)  cmd_generate ;;
    up)        cmd_up ;;
    down)      cmd_down ;;
    restart)   cmd_restart ;;
    status|ps) cmd_status ;;
    logs)      cmd_logs "${1:-}" ;;
    clean)     cmd_clean ;;
    help|--help|-h) usage ;;
    *)
      err "Unknown command: ${cmd}"
      usage
      ;;
  esac
}

main "$@"
